### ISSUE TITLE
Logout users with expired credentials

### ISSUE THREAD

**Issue by Allcharles** [Allcharles/workbench-client#1640]
Currently, when a user with expired credentials attempts to make any API requests, they are met with an Unauthorized Access error message. Workbench-client should make a `GET /security` request to determine if the credentials are still valid, and if not, log out the user automatically.

**Comment by Allcharles** [comment]
If auth token is expired, cookie should also be expired
If cookie expired (401), re-direct to login page similar to error handler
Store auth token in session service so it is destroyed on refresh
When requesting data, check if auth token exists, if not request `/security` to get auth token

**Comment by atruskie** [comment]
```diff
- When requesting data, check if auth token exists, if not request /security to get auth token
+ On angular first load, check if auth token exists, if not request /security to get auth token
+ We can fail to get an auth_token without then triggering/forcing a login
```

Basically, we're just going to emulate the behaviour of the old client and just pull the token whenever angular loads.
Main point is not to cache the auth_token's value in local storage. That way we won't get in a state where token is desynced with session cookie

Note I just thought about cases where we have anonymous users... I think we should just allow auth_token fetch to return `null` in cases where we are not logged in.
