### ISSUE TITLE
Adding filters to the recording's list page

### ISSUE THREAD

**Issue by ninascarpelli** [Allcharles/workbench-client#1724]
**Is your feature request related to a problem? Please describe.**
There are just too many recordings and it would be useful to have a filter for when you're looking for a specific date, for example.

**Describe the solution you'd like**
A filter feature from the recording's list page.

**Describe alternatives you've considered**
False Colour Visualisation can make it faster to find specific date/time, but if it's not working or you don't want to use it, then filtering would be helpful.

**Additional context**
I'm referring to add a filter in this page:

![image](https://user-images.githubusercontent.com/42744528/145305609-5782a09d-b166-42a0-84be-bc61797b1707.png)

**Comment by hudson-newey** [comment]
I have created a mock up of how this filter would work, to keep in line with the historical design language seen on the batch downloading component, I am going to create a common a new date/time filter component that I can use on both pages.

![image](https://user-images.githubusercontent.com/33742269/217414039-de3df245-b2f7-4001-b215-da6ee47b00e6.png)

_Edit: Updated image to reflect requested changes_

**Comment by atruskie** [comment]
Filters should be hidden by default and shown when a filter button is activated.

We also need some kind of context for the filter panel. e.g. a title like _filter recordings_

otherwise; yes, component reuse is required. Good start
