### ISSUE TITLE
Wrong timezone given for audio recording recordedAt field

### ISSUE THREAD

**Issue by Allcharles** [Allcharles/workbench-client#1815]
`AudioRecording` model has two fields; `recordedDate` and `recodedUtcOffset` which are of importance. The baw server returns the `recordedDate` using a UTC offset currently. This means that in places, we are displaying the wrong value, such as the audio recordings list pages.

Example:
https://data.acousticobservatory.org/projects/1/regions/16/points/61/audio_recordings
Audio recordings tooltips show that the timezone is in Australia/Perth, however the actual displayed values are in UTC.

**Comment by atruskie** [comment]
This should be dealt with by #1736

**Comment by Allcharles** [comment]
This was temporarily patched in #1820
