### ISSUE TITLE
Add time of day filter to batch downloader

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1829]
In our batch download audio page:

Add filters for time of day to filter out recordings that did not occur at that time of day.

Filter endpoints should inclusively match any overlaps of any recordings.

i.e. Time of day filter 09:00 - 11:00 would match the 08:00-10:00 recording and also the 10:00-11:00 recording for any days within the currently selected date ranges.

**Comment by Allcharles** [comment]
Currently blocked by https://github.com/QutEcoacoustics/baw-server/issues/562

**Comment by atruskie** [comment]
If the date range of the a query crosses a DST boundary we should let the user know there is some funkyness going on:

> Your filter crosses a DST change point. The first date's time of day will be used for all recordings in your query.

I've tried to explain this to a few non-technical people now and I think my suggestion of defaulting to a fixed UTC offset derived from the first recording that satisfies a query is appropriate.

**Comment by atruskie** [comment]
BTW the UI components to add include:

- checkbox/switch for enabling time of day filtering
- time of day field start (local)
- time of day field end (local)
- checkbox "ignore DST" with explainer tooltip

**Comment by atruskie** [comment]
Closed by #1852
