### ISSUE TITLE
Add button and badge to projects showing/editing allow original download options

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1831]
**Is your feature request related to a problem? Please describe.**

Currently a user cannot control whether original downloads are enabled for their project.

This means anyone in Ecosounds cannot turn this option on (we've turned it on by default for the A2O since all that data shares the same license).

**Describe the solution you'd like**

- Add a form control to the project edit page that allows owners to change this setting
- Add a badge in the actions menu that indicated the present value of this setting.

**Comment by Allcharles** [comment]
Design Notes:

- Suggested title: Allows downloads
- Maybe consider an icon for the yes/no
- Maybe have a tooltip that can explain further, especially if disabled
  - "The owner of this project has chosen to not allow downloading whole audio recordings"
- Try to make the widget text fit on one line - so not a heading
