### ISSUE TITLE
Google maps view defaulting to Google Headquarters

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1870]
**Describe the bug**

When I look at a site or project page, the google maps view appears to be centered on Google Headquarters in the USA.

**To Reproduce**

1. Go to any Ecosounds project that has markers for its children
2. Observe the map pointing at an unfamiliar urban landscape
3. Zoom out to the see the focus on the US, and eventually the markers all over in australia

**Expected behavior**

The map should be centered around the markers

**Screenshots**

<img width="695" alt="image" src="https://user-images.githubusercontent.com/1452968/160731390-6eac9678-e26a-48dc-83ea-25f4b40e5343.png">

![image](https://user-images.githubusercontent.com/1452968/160731316-bc9e3537-bab5-4c87-9590-0b938ef93d62.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome 
- Version: 99.0.4844.74

**Additional context**

The problem appears mitigated after refreshing the page.

It does seem related to a hard refresh cycle - navigating to another project demonstrates the problem again

**Comment by Allcharles** [comment]
Need to validate if this is still broken, but it appears to have fixed itself. Seems this was an issue with googles map bundle

**Comment by atruskie** [comment]
I can no longer reproduce this. Closing.
