### ISSUE TITLE
Recording date for Audio Recordings shows Invalid Date

### ISSUE THREAD

**Issue by Allcharles** [Allcharles/workbench-client#1879]
There appear to be some dates in the baw-server database for staging and ecosounds data which uses the friendly name for `recordedDateTimezone`. This causes luxon to show the date as `InvalidDate`. A better solution is to attempt to convert the date by replacing `'-'` with `'/'`, and `' '` with `'_'`. If the date to use the timezone, the model should use UTC as a fallback and update `recordedDateTimezone`.

**Comment by atruskie** [comment]
This was just resolved by https://github.com/QutEcoacoustics/baw-server/commit/9048a3f752f95583b3a384d750bbc6bbef07fc08
