### ISSUE TITLE
Batch download instructions: change step 4 to "open powershell"

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1882]
User feedback suggested it would be good rename step 4 of our instructions to say _Open PowerShell_ instead of mentioning a terminal.

Relevant screen:

![image](https://user-images.githubusercontent.com/1452968/162363079-0dc415c9-d5ab-4cbc-8c8c-e4341b32a7ac.png)

**Comment by Allcharles** [comment]
Relates to #1838
