### ISSUE TITLE
Harvest interface

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1888]
**Is your feature request related to a problem? Please describe.**

https://github.com/QutEcoacoustics/baw-server/issues/539 is creating APIs for harvesting.

**Describe the solution you'd like**

Expose UIs to allow users to harvest.

**Describe alternatives you've considered**

PowerShell scripts only for a2o uploads...

**Additional context**

There is an existing design which needs to be resurrected.

Also extensive design time will need to be put into to  establish the correct workflow.

**Comment by Allcharles** [comment]
Proposed design improvements:
![image](https://user-images.githubusercontent.com/3955116/178426641-1705b0e0-c63c-475f-bf3d-fc4dd85faa24.png)
