### ISSUE TITLE
Bulk audio download: don't show command when a user is not logged in

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1930]
From user testing: when users are not logged in they tend to just copy and paste the download command without realising that the `"INSERT_AUTH_TOKEN"` here token needs  to be replaced.

Instead we should hide the command and only show it when someone is logged in. If they're not logged in we should have a warning panel in place of the command with a message like _log in to see command_..

**Comment by hudson-newey** [comment]
I have created a mock up of the requested UI changes on a local branch

![image](https://user-images.githubusercontent.com/33742269/210288305-aac0d1fc-c31b-4a8f-a16a-9c26efeae07e.png)
