### ISSUE TITLE
Harvest: upload screen - instructions clarification

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1956]
-  Move "when you are finished uploading" to the numbered steps in the previous section
- switch instructions to cards?
   -  Use a wired network connection and not wifi - with cancel icon overlayed on wifi icon
   - add a card for created folders 
      - explain the format is <sitename_id>
      - give an example
      - hide the card if there are no sites/points in the project
   - you can create your own folders card
   - split files into folders based on sensor

**Comment by Allcharles** [comment]
![image](https://user-images.githubusercontent.com/3955116/179435157-60a11bb5-d8bf-4da7-9ade-5732ae5279c4.png)
