### ISSUE TITLE
harvest: upload list page created datestamp column should not show dates in UTC

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1977]
From production usage:

![Image](https://user-images.githubusercontent.com/1452968/182524221-929e8042-3135-4c3e-91b8-7dc58b296f07.png)

**Comment by hudson-newey** [comment]
In the same PR that will resolve this issue, I will also be fixing a similar bug on the audio recordings list page

![image](https://user-images.githubusercontent.com/33742269/212782116-55bb6f6a-7fcf-4e5f-b332-59e5de059671.png)
