### ISSUE TITLE
Add support for naming harvests

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1996]
**Is your feature request related to a problem? Please describe.**

Keeping track of harvests is kind of hard.

**Describe the solution you'd like**

The server added support for names via https://github.com/QutEcoacoustics/baw-server/issues/619.
All harvests have a default name; expose the name and allow the name to be editted.

- show the name in the table in the harvest list component
- show the name in the header on all screens on harvest details page
- allow editing the name
  -  on the uploading, metadata review, and completed screens
  - via an inline field (pencil icon used to swap span for input)
  - with no explicit save

**Describe alternatives you've considered**

Default name - which are implemented by the server.

**Comment by hudson-newey** [comment]
Screenshots of UI changes
![image](https://user-images.githubusercontent.com/33742269/196583303-4f60a781-b1f7-4c84-9c62-6852691e4321.png)
![image](https://user-images.githubusercontent.com/33742269/196583338-c98314dd-6587-4934-85f2-647531e3dee2.png)

**Comment by atruskie** [comment]
- Than edit icon should be aligned to baseline
- The text `Harvest` is not used in our UI lexicon and should not be present
- that input doesn't look styled correctly - are you using the correct bootstrap classes
- ensure there is some visual feedback for name change updates (probably a toast)
- The name should probably be in the h1 next to _Upload Recordings_
