### ISSUE TITLE
Creating new harvest causes title component to query uninitialised attributes

### ISSUE THREAD

**Issue by hudson-newey** [Allcharles/workbench-client#2000]
**Describe the bug**
The Harvest title component now requires a Harvest model in order to operate. However, when a user creates a new Harvest, I suspect this model isn't generated until they proceed with the "Start streaming upload" or "Upload batch" buttons. This causes the browser console to throw the JS runtime error seen bellow.

**To Reproduce**

1. Go to "Projects"
2. Click on a project
3. Click on "New Upload"
4. Open Browser Developer Tools
5. Observe the error described above

**Expected behaviour**
There should be no browser

**Screenshots**
![image](https://user-images.githubusercontent.com/33742269/200180535-56b25641-6968-42eb-b3e0-c465333cb5e9.png)

**Desktop (please complete the following information):**

- OS: all
- Browser Chrome & Firefox
- Version all

**Additional context**  
This is a regression bug from #1999   
This does not prevent a user from creating a Harvest

**Comment by atruskie** [comment]
Well spotted
