### ISSUE TITLE
Add a WIP download analyses button to the audio recording list table and the audio recording details page

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#2009]

**Comment by hudson-newey** [comment]
Screenshots of mock ups for WIP download analyses button
![image](https://user-images.githubusercontent.com/33742269/203886576-896428ac-7611-41ab-8705-c4df2232eb7a.png)
![image](https://user-images.githubusercontent.com/33742269/203887273-bda627c5-3f89-41f4-8d13-006742bf8fc1.png)

The `baw-wip` component could not be used in the audio recording list table as it has vertical height that would drastically change each rows vertical height.

The download analyses button was added to the menu list in the details component to keep in line with the design language of the component; where every actionable button is in this menu bar. This can be easily changed, and can make use of the `baw-wip` component if moved to the base of the page. The disabled menu item is in line with the design philosophy as similar disabled menu items can be seen in the profile component.
