### ISSUE TITLE
Instrutions for Metadata Review stage in Harvest only loads once a folder change has occured

### ISSUE THREAD

**Issue by hudson-newey** [Allcharles/workbench-client#2015]
**Describe the bug**
When the user first navigates to a Harvest metadata review page, the instructions on "How to handle files which need attention" and "How to handle problem files" are not loaded until a file change occurs.

This causes the visuals to jump suddenly when the user first clicks a folder.

**To Reproduce**

1. Go to a project
2. Click on Recording Uploads
3. Click on a Harvest with the stage "MetadataReview"
4. Observe that instructions on the right hand side are not rendered until a folder is opened

**Expected behavior**
The instructions on the side panel are loaded as soon as the page is loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/33742269/206048442-d8aad584-e8c0-497e-a4d8-699d74f6ac2e.png)
![image](https://user-images.githubusercontent.com/33742269/206048493-aed8537a-4632-4e7b-8448-287fb164a495.png)

**Desktop:**

- OS: Fedora (Linux)
- Browser: Chrome, Firefox
- Version: Latest

**Comment by atruskie** [comment]
Expected behaviour is that help is displayed as needed, on-demand.

If there is visual jumping, then perhaps we can change how it appears, but otherwise this is working as intended.

Waiting for comments.

**Comment by hudson-newey** [comment]
Ok, makes sense. The visual jump doesn't automatically scroll the view finder, so I'd say this is working as expected

I'll be closing this ticket if there are no further comments
