### ISSUE TITLE
Batch download filter payload is submitting a short-year date

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#2018]
**Describe the bug**

```
 {"filter"=>{"sites.id"=>{"eq"=>307}, "recorded_date"=>{"greater_than_or_equal"=>"2020-12-29"}, "recorded_end_date"=>{"less_than_or_equal"=>"20-12-31"}}, "paging"=>{"page"=>1}, "format"=>"json", "controller"=>"audio_recordings", "action"=>"filter", "audio_recording"=>{}}
```

This payload was submitted by the batch download page. It looks like somehow the user managed to submit a short form date string for the less_than_or_equal component.

**To Reproduce**

Not sure, try and type the short date in the form inputs. I'm pretty sure we validated for this.

**Expected behavior**

The server expects only long form years for dates.

---

Related to: https://github.com/QutEcoacoustics/baw-server/issues/639

**Comment by hudson-newey** [comment]
I was able to reproduce this bug by manually inputting the dates into the input field. Should be pretty easy to fix given that we already validate input for this field.

![image](https://user-images.githubusercontent.com/33742269/212800703-a9a07e7e-3edf-40df-b388-36bb203bb8e2.png)

To resolve this issue I'm going to be modifying the conditions on the validator to assert that the input does not contain a short date.

**Other possible solutions:**
- Automatically convert short date formats to long date format
- Stop users from manually inputting dates

_Other Notes:_
There seems to be a similar issue related to the user being able to use out of boundary dates by manually inputting dates. I'll be fixing this in the same PR
