### ISSUE TITLE
Inconsistencies in ngTable alignment

### ISSUE THREAD

**Issue by hudson-newey** [Allcharles/workbench-client#2031]
**Describe the bug**
Navigating to the audio recording & harvest upload pages via the site menu vs navigating via url / pressing the refresh button causes the ngTable to have different widths.

**To Reproduce**

1. Navigate to a project
2. Click on Audio Recordings
3. Observe the width of the ng table & location of the menu
4. Refresh the page using `f5` or navigate to the URL by pasting the URL in the url bar of your browser
5. Observe that the width of the audio recordings table now stretches the length of the screen

**Expected behavior**
Pages with an ng table should be displayed the same regardless of how the user navigates to it

**Screenshots**

### Harvest Uploads:

**Navigating to the page via the menu item:**
![image](https://user-images.githubusercontent.com/33742269/213040009-1b9d0069-3b00-41aa-b8a3-0cda95bd75a3.png)

**After page refresh:**
![image](https://user-images.githubusercontent.com/33742269/213039752-250375af-85b1-40cb-a900-ff9d22a842b9.png)

_Same bug is observed on the audio recordings list view_

**Desktop (please complete the following information):**

- OS: Windows & Linux
- Browser Chrome, Firefox, & Edge
- Version Chrome: 109.0.5414.75, Firefox: 102.6.0esr, Edge: 109.0.15.1518.55

**Comment by atruskie** [comment]
I think this was previously identified; Charles wanted to replace ngTable because there were a host of problems with it.

I think look in the ng table repo for some hint of the problem.

**Comment by hudson-newey** [comment]
In retrospective, this seems to be a duplicate of #1935 and will be resolved if #1730 is successful

I'll be closing this ticket
