### ISSUE TITLE
Sketch out client side UI for acoustic event summary report generator & Acoustic Event Summary Report

### ISSUE THREAD

**Issue by hudson-newey** [Allcharles/workbench-client#2058]
Acoustic event summary report generator - a filter page, similar to the batch audio recording download page with the appropriate filter condition inputs

Acoustic event summary report - There should be two options to view, print, and download a report from the acoustic event summary report generator page.

Viewing the page _may_ take you to a new route that has the report in HTML format. From here you can print the page / export to PDF with Ctrl + P or by clicking the "Print" icon / button in a menu tray.

**Comment by atruskie** [comment]
We'll likely have a print button/link to that will enable the print styles for previewing and stuff

**Comment by hudson-newey** [comment]
**Report Generator UI Mock Up**

I have made a rough draft for the summary report generator
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/3f995608-2643-4822-a196-fcb283020ef4)

I have also created another draft using our `baw-form` component which I think aligns better to the existing style of the client, but also feels cluttered
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/dcdfb7e0-215a-4622-a74c-cd6afed04738)

**Report UI Mock Up**
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/7b33daf1-895d-49b3-bdac-4c2812c3e91c)

I will be working on a way to expand the "confidence plot" width so it can support larger graphs, but aside from that, the mock ups are fully done

A mockup of the printable PDF report can be found below
[summary_report_draft.pdf](https://github.com/QutEcoacoustics/workbench-client/files/11561251/summary_report_draft.pdf)

**Comment by atruskie** [comment]
OK; this looks pretty good. 

You should style the form as per our current conventions, though you can probably make a more compact version.
Pretty much it should seamlessly blend in. I'd be reusing the date and time range filter component from the audio recording search list page.

I think next steps is show this report in the print media version.

**Comment by hudson-newey** [comment]
An example using [Google's Material Design (chips)](https://material.angular.io/components/chips/overview#autocomplete)

using the [Indigo + Pink premade theme](https://miro.medium.com/v2/resize:fit:1400/1*XJ3gUbWQOlgWV8JZIHnTLQ.png). From what it looks like it might be possible to create a [custom theme](https://indepth.dev/posts/1320/custom-theme-for-angular-material-components-series-part-1-create-a-theme) that uses our existing bootstrap styles + overrides (although this will be a similar process, it will be significantly more time consuming to develop and maintain than our bootstrap custom theming, and will possibly break with updates to either bootstrap or material theming)

**With dropdown**
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/ccb21bab-0d57-4548-8e48-b750128fe664)

**With multiple items + no dropdown**
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/4ef8574e-8a20-4e13-84a3-5c5e7c051316)

**We don't have a direct equivalent on the current client but for reference: what ng-bootstrap dropdowns looks like on the current client**
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/82e67c3c-7e6e-4430-b140-32554274e929)

**Comment by atruskie** [comment]
We discussed offline: the layout looks good but material is a non-starter because it uses sass variables for theming making it incompatible with our css variables solution (how many times must I forget this lol).
