### ISSUE TITLE
Can't submit any forms on the website

### ISSUE THREAD

**Issue by stephan-jacobs** [Allcharles/workbench-client#2073]
**Describe the bug**
I go to the Register page on the website, fill in my details and hit register. No matter how many usernames/passwords I try I get an error saying:

> "Http failure response for https://api.ecosounds.org/my_account: 500 Internal Server Error"

Then I tried to report a bug using the online form and got:

>"Http failure response for https://api.ecosounds.org/bug_report: 500 Internal Server Error"

I also tried to register on a smartphone where I got:

>"Http failure response for https://api.ecosounds.org/my_account: 500 OK"

**To Reproduce**

1. Go to https://www.ecosounds.org/report_problem
2. Fill in your details
3. Click submit

Same deal for Registering an account.

**Expected behavior**
I expect to see some kind of acknowledgement that the form has been submitted rather than staying on the same page and seeing an error message.

**Screenshots**
![image](https://github.com/QutEcoacoustics/workbench-client/assets/46317074/90682af3-5b7d-4a22-8829-643297768101)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.3 LTS x86_64
- Browser: Firefox
- Version: 116.0.3 (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone Xs Max
- OS: iOS 16.6
- Browser: Safari
- Version: The one that comes with iOS 16.6 I guess?

**Additional context**
Seems like a serverside thing to me but I'm no expert :)

**Comment by atruskie** [comment]
Hi @stephan-jacobs I can replicate your problem - thanks for letting us know. 

It looks like we went over our limit for sending emails this month.  The good news is that it should reset in just a few hours. I'll check back tomorrow to see if everything is working.

**Comment by atruskie** [comment]
Ok it should be working now. Let me know if you have any more issues.

**Comment by stephan-jacobs** [comment]
Thanks Anthony! It works for me now :) Much appreciated
