### ISSUE TITLE
Intermitent bug where primary menu items which require authentication don't show on reload

### ISSUE THREAD

**Issue by hudson-newey** [Allcharles/workbench-client#2084]
**Describe the bug**
Approximately 70% of the time when I reload the A2O project details page (using `Ctrl + R` or `F5`) it doesn't show the primary menu action items that I need to be authenticated for.

**To Reproduce**

1. Authenticate yourself using the "Log In" page
2. Go to [https://data.acousticobservatory.org/projects/1](https://data.acousticobservatory.org/projects/1)
3. Refresh using `Ctrl + R` or `F5` and observe that (approximately) 70% of the time, "Recording Uploads", "New Site", "Edit this project", and "Edit Permissions" aren't shown

**Expected behavior**
All primary menu items which I have access to should be shown when refreshing the page

**Screenshots**

![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/46fb31af-1dd9-451b-b44a-aa81c2e11077)
**Screenshot of my account being logged into the A2O without all menu items present**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 119.0b8

**Comment by atruskie** [comment]
Related to #1979 ?

In that case I suspected it was the resolvers doing caching.

**Comment by hudson-newey** [comment]
> Related to #1979 ?
> 
> In that case I suspected it was the resolvers doing caching.

Appears to be the same bug, however, I'm not 100% sure if this is due to resolver caching

Another strange point of note is I can't replicate either #1979 or this issue on staging or Ecosounds, only A2O.
I've also tried setting "hideProjects": true in the development environment settings, but I can't replicate it with projects hidden either.

I'll be closing the issue nonetheless because resolving #1979 will resolve this issue too
