### ISSUE TITLE
Add Open Ecoacoustics logo to readme and website

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#2087]
This project is sponsored by and is part of the open Ecoacoustics platform.

- [x] Add logo to readme 
- [x] and to the home page
- [x] Make logo link to open Ecoacoustics website.

**Comment by hudson-newey** [comment]
**Mock-up of home page styling**

![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/0427cd39-39cc-4a58-9737-7bd263887edd)

**Alternative**

![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/d43d3837-15f9-4ae2-ac58-3685752df7f3)
