### ISSUE TITLE
HTTP 500 when creating account or trying to report problem 

### ISSUE THREAD

**Issue by emilysoaring** [Allcharles/workbench-client#2142]
**Describe the bug**
Attempted to register to access data, but the site fails with a red popup indicating "Http failure response for https://api.acousticobservatory.org/my_account/: 500 OK". The same error occurs (except with the bug_report API dest) when I tried to use the Report Problem link.

**To Reproduce**
For registration:
1. Provided, username, email, password & password again.
2. Click register
3. Red popup appears with `Http failure response for https://api.acousticobservatory.org/my_account/: 500 OK`. Page does not change. 

In case creation was working and the failure was in the response page generation (given the OK component in response), I tried to do password recovery for the hopefully newly created account - but no email was received, suggesting account was not created.

Tried a few variations with no success:
* Password without special characters
* Alternate email (with a more typical TLD)
* Alternate username (in case it was taken)

Upon trying to submit this report via [Report Issue](https://data.acousticobservatory.org/report_problem), it also throws the same `Http failure response for https://api.acousticobservatory.org/bug_report: 500 OK`

**Expected behavior**
Successful account creation
Receipt of typical email address verification email
Click email link to verify email.
Access to A2O dataset.

**Desktop (please complete the following information):**
Fedora Core 39
Firefox 125.0.2

**Comment by atruskie** [comment]
Thanks for the report, I'll look into it soon 🙂

**Comment by atruskie** [comment]
I've looked into it and this problem should resolve itself automatically within 3 days.

In the meantime, please feel free to email me at `a dot truskinger at qut dot edu dot au`
